# Generated by Django 2.0.5 on 2019-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191126_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/books'),
            preserve_default=False,
        ),
    ]
