# Generated by Django 2.0.5 on 2019-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
