version: '3'

services:
  db:
    image: postgres
    networks:
      - webappnetwork
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - webappnetwork
    depends_on:
      - db
  frontend:
    build: ./front
    volumes:
      - ./front:/front
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start
    networks:
      - webappnetwork
networks:
    webappnetwork:
        driver: bridge
