# Generated by Django 2.0.5 on 2019-11-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('log_type', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
